#!/bin/bash

docker run \
    -v $(pwd)/store/etc/voicer:/etc/voicer \
    -v $(pwd)/store/var/log:/var/log \
    -e VOICER_CONFIGFILE=/etc/voicer/config \
    -p "3000:3000" \
    -p "3100:3100" \
    -it antirek/voicer voicer